language: nodejs
cache:
  directories:
    - ~!@/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'url-personaliza.com' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $github_token
  local-dir: dist/
  target-branch: master
  commit_change: "Deploy release ${TRAVIS_TAG}"
  on: 
    branch: develop

