language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'cv.HaroldCarhuancho.dev' > public/CNAME
deploy:
  name: harold@vis
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_change: "harold@vis - Deploy release ${TRAVIS_TAG}"
  fqdn: cv.HaroldCarhuancho.dev
  on: 
    branch: development

